douglaskline/trucktrackrepo

.vscode/launch.json, .vscode/tasks.json, trucktrack/ui/ui.csproj
user secrets are set up
have not configured the project to retrieve the connection string from the user secrets yet
closes issue #70
=> Issue 70 setup user secrets for the database connection in the UI project

docs/ScaffoldControllerViewCommands.md, trucktrack/dal/trucktrackContext.cs, trucktrack/dal/trucktrackContextFactory.cs, trucktrack/ui/UserController.cs, trucktrack/ui/Views/User/Create.cshtml, trucktrack/ui/Views/User/Delete.cshtml, trucktrack/ui/Views/User/Details.cshtml, trucktrack/ui/Views/User/Edit.cshtml, trucktrack/ui/Views/User/Index.cshtml, trucktrack/ui/ui.csproj
closes issue #75 
fyi - messed up on a commit for issue #74 
left the connection string to our actual database in
have removed it from this commit, and changed the password
to be more secure, we could
* change the username
* change the database name / url
=> Issue 75 scaffold a user controller that connects to the class database

classProjects/MIS328/Project3/Proj3zacharyserfling.md
=> Issue 59 zach project 5

classProjects/MIS328/Project3/Proj3cwl8528.md
=> Issue 61 conner project 5

classProjects/MIS328/Project3/Proj3billtnguyen.md
=> Issue 62 bill project 5

classProjects/MIS328/Project3/Proj3rrr2439.md
=> Issue 64 robert project 5

classProjects/MIS328/Project3/Proj3ReidWatters.md
=> Issue 60 julia project 5

trucktrack/ui/wwwroot/starter.html
=> made the file and tested it locally

classProjects/MIS328/Project6/AzriAmirHakim.md
=> Issue 106 azri project 6

classProjects/MIS328/Project3/Proj3nv8663.md
=> Issue 107 noah project 5

classProjects/MIS328/Project6/folderpurpose.md
Project 6 Completion 
closes #103
=> Issue 103 dani rowe project 6

classProjects/MIS328/Project3/Proj3yopinq.md
=> Issue 84 yopi project 5

classProjects/MIS328/Project3/Proj3cdh5809.md
=> Issue 83 chris hensley project 5

classProjects/MIS328/Project6/BillNguyen.md
=> Issue 88 bill nguyen project 6

classProjects/MIS328/Project6/Proj6rrr2439.md
=> Project 6 file changes

classProjects/MIS328/Project6/JuliaWatters.md
=> Issue 85 julia project 6

classProjects/MIS328/Proj3AzriAH.md
=> Issue 81 azri project 5

classProjects/MIS328/Project3/Proj3AubreyBordeaux.md
=> Issue 55 project 3 for aubrey bordeaux

trucktrack/ui/wwwroot/MIS328Proj8/BillNguyen.html
=> Issue 152 bill nguyen project 8

classProjects/MIS328/Project6/zacharyserfling.md
=> Project 6 VS Code Commit

trucktrack/ui/wwwroot/MIS328Proj8/JuliaWatters.html
=> Issue 144 julia watters project 8

trucktrack/ui/wwwroot/MIS328Proj8/DaniRowe.html
=> Issue 147 project 8

trucktrack/ui/wwwroot/MIS328Proj8/AzriAmirHakim.html
=> Issue 145 azri amir hakim project 8

trucktrack/dal/TruckEntityTypeConfiguration.cs, trucktrack/dal/truck.cs, trucktrack/dal/trucktrackContext.cs
i have created ;
>>truck.cs file
>>TruckEntityConfiguration.cs file
and i have added added TruckEntityTypeConfiguration into the trucktrackContext.cs file
=> Issue 163 create a model class for truck which represents a food truck

classProjects/MIS328/Project6/ChrisHensley.md
=> my change to Project 6

trucktrack/dal/Migrations/20220216235244_thirdMigration.Designer.cs, trucktrack/dal/Migrations/20220216235244_thirdMigration.cs, trucktrack/dal/Migrations/InitialMigration.sql, trucktrack/dal/Migrations/SecondMigration.sql, trucktrack/dal/Migrations/thirdMigration.sql, trucktrack/dal/ReportEntityTypeConfiguration.cs, trucktrack/dal/report.cs
made the change, did the migration, and executed the sql script in our database
=> Issue 178 make the user id in report allow nulls

trucktrack/trucktrack.sln
close the issue #181 , we verified that it is working in my Machine HP and Dr Kline`s machine
=> change the solution file for HP laptops to work

docs/EFMigrationsCommands.md, docs/ScaffoldFeb17.md, trucktrack/ui/Controllers/locationController.cs, trucktrack/ui/Controllers/reportController.cs, trucktrack/ui/Controllers/truckController.cs, trucktrack/ui/Views/location/Create.cshtml, trucktrack/ui/Views/location/Delete.cshtml, trucktrack/ui/Views/location/Details.cshtml, trucktrack/ui/Views/location/Edit.cshtml, trucktrack/ui/Views/location/Index.cshtml, trucktrack/ui/Views/report/Create.cshtml, trucktrack/ui/Views/report/Delete.cshtml, trucktrack/ui/Views/report/Details.cshtml, trucktrack/ui/Views/report/Edit.cshtml, trucktrack/ui/Views/report/Index.cshtml, trucktrack/ui/Views/truck/Create.cshtml, trucktrack/ui/Views/truck/Delete.cshtml, trucktrack/ui/Views/truck/Details.cshtml, trucktrack/ui/Views/truck/Edit.cshtml, trucktrack/ui/Views/truck/Index.cshtml
scaffolded truck, location, report
all controllers and views created
=> Issue 180 scaffold a truck controller

trucktrack/ui/wwwroot/MIS328Proj8/KishawnaBell.html
project 8 created web page using bootstrap.
=> Issue 173 kishawna project 8

classProjects/MIS328/Project6/kishawnabell.md
=> Issue 110 kishawna project 6

trucktrack/ui/wwwroot/MIS328Proj8/AubreyBordeaux.html
=> Issue 150 aubrey proj8

trucktrack/ui/wwwroot/MIS328Proj8/RobertR.html
=> Issue 153 robert project 8

classProjects/MIS328/Project6/YopiInquimboy.md
=> Issue 124 yopi project 6

trucktrack/ui/wwwroot/MIS328Proj8/ChrisHensley.html
=> Changes to Project 8

trucktrack/dal/truck.cs, trucktrack/daltests/TruckModelTests.cs, trucktrack/daltests/UnitTest1.cs, trucktrack/daltests/daltests.csproj, trucktrack/daltests/readme.md
added an xunit testing project called daltests
it shows some examples, and can be run by
- go to terminal
- change to the daltests subdirectory
- issue command: dotnet test
-
=> Issue 222 add xunit testing project

trucktrack/ui/Views/truck/Details.cshtml
removed timestamp from Details view
=> Proj 9 - Removed timestamp from Details view

trucktrack/ui/Views/report/Index.cshtml
=> Issue 212 Project 9 Alaina

trucktrack/ui/Views/truck/Index.cshtml
=> Issue 194 chris proj 9

trucktrack/ui/Views/User/Edit.cshtml
=> Removed layout = null lines

trucktrack/ui/Views/report/Delete.cshtml
=> Deleted DD NameFor & DT class DisplayFor timestamp

trucktrack/ui/Views/location/Index.cshtml
=> deleted timestamp column from index.csht

trucktrack/ui/wwwroot/MIS328Proj8/NoahVu.html
=> Issue 185 noah project 8

trucktrack/ui/Views/User/Details.cshtml
removed Layout=null; line from user details view
closes #190
=> Project 9 Changes, removed Layout=null; line from user details view

trucktrack/ui/wwwroot/MIS328Proj8/AlainaMitchell.html
=> Issue 154 alaina mitchell project 8

classProjects/MIS328/Project6/zacharyserfling.md
=> Project 11 - Step 7

classProjects/MIS328/Project6/JuliaWatters.md
=> Project 11 Edited line 12 

classProjects/MIS328/Project6/AubreyBordeaux.md
=> Project 11- line 12 change A

classProjects/MIS328/Project6/Proj6rrr2439.md
=> Project 11A - Change to line 4

classProjects/MIS328/Project6/YopiInquimboy.md
edited and changed line 12 from Nike -> Crocs
=> Project 11 - changes made to line 12

classProjects/MIS328/Project6/kishawnabell.md
=> made change to line 12

classProjects/MIS567/MIS567Project2/aysun.md
@douglaskline  i need your approval and merge please
=> i wrote something to the line 2 for Project 7 item A

trucktrack/utiltests/AmirHakimProj13.cs
=> Issue 365 amir hakim project 13

trucktrack/utiltests/NguyenProj13.cs
=> Issue 364 nguyen project 13

classProjects/MIS328/Project6/BillNguyen.md
=> Made a change to line 12 B

classProjects/MIS328/Project6/JuliaWatters.md
=> Project 11 Edited line 12 Conflict Resolved

classProjects/MIS328/Project6/AzriAmirHakim.md
=> Proj 11 added "that" to line 10

classProjects/MIS328/Project6/Proj6rrr2439.md
=> Project 11B - Made change to line 4

classProjects/MIS328/Project6/kishawnabell.md
added another change to line 12
=> changed line 12 again

classProjects/MIS567/MIS567Project2/aysun.md
@douglaskline @nischalsaladi i need approval and merge to main please for project 7 item B
=> 341 project aysun karamustafaoglu item b

trucktrack/utiltests/WattersProj13.cs
=> Project 13 Watters 

trucktrack/utiltests/SerflingProj13.cs
Zachary Serfling's completed Project 13
=> Project 13 Serfling Completed

trucktrack/utiltests/utilTest1.cs
=> Issue 403 nguyen project 14

classProjects/MIS567/MIS567Project2/jamesdupree.md
@nischalsaladi @AysunKaramustafaoglu @hvanderhoof Could you guys be so kind to approve this.
=> made a change to line 1 in jamesdupree.md

classProjects/MIS567/MIS567Project2/hbv8715.md, classProjects/MIS567/MIS567Project2/lk2255.md
=> Issue 444 project 7 kness todo item a

trucktrack/utiltests/utilTest1.cs
Created NSdistance unit test between Tap Tea Bar and Chopt
=> Issue 435 bell project 14

trucktrack/dal/Migrations/location.sql
@douglaskline @AysunKaramustafaoglu I have added the locations to the sql file. If you can check it and give me feedback on this.
=> locations file made and sql query added to file

trucktrack/ui/wwwroot/MIS567Proj8/LindsayKness.html
=> Created html file for Project 8

trucktrack/utiltests/KnessProj13.cs
Finished project, used 2 coffee shops.
=> Issue 427 kness project 13

trucktrack/utiltests/NischalProj9.cs
@douglaskline  @AysunKaramustafaoglu  Could you approve it please.
=> I edited the file for Proj9

trucktrack/ui/wwwroot/MIS567Proj8/JamesDupree.html
=> working table

trucktrack/dal/TruckEntityTypeConfiguration.cs, trucktrack/dal/truck.cs, trucktrack/ui/Views/truck/Details.cshtml, trucktrack/ui/wwwroot/truckDetailMockup.html
Working details page /ui/truck/details.cshtml with correctly displayed names
=> Issue 259 make the truck/details cshtml view functional
